### ISSUE TITLE
关于 - LHK's Blog

### ISSUE THREAD

**Issue by Linhk1606** [Linhk1606/blog-source#4]
https://blog.lhkstudio.me/about/

**Comment by Linhk1606** [comment]
test

**Comment by MHuiG** [comment]
我明白了，你禁用了 hexo-offline 插件，因此之前的用户无法更新缓存。而且是永远无法更新。

![image](https://user-images.githubusercontent.com/38281581/80274974-ec2fbf00-8710-11ea-8a74-c47c8149a7ce.png)

用Gitalk还不如直接跳转到GitHub Issues评论

**Comment by Linhk1606** [comment]
> @MHuiG
> 
> 我明白了，你禁用了 hexo-offline 插件，因此之前的用户无法更新缓存。而且是永远无法更新。
> 
> ![image](https://user-images.githubusercontent.com/38281581/80274974-ec2fbf00-8710-11ea-8a74-c47c8149a7ce.png)
> 
> 用Gitalk还不如直接跳转到GitHub Issues评论
> 

emm那我该怎么办? 装回去吗(╬▔皿▔)╯

**Comment by MHuiG** [comment]
> > @MHuiG
> > 我明白了，你禁用了 hexo-offline 插件，因此之前的用户无法更新缓存。而且是永远无法更新。
> > ![image](https://user-images.githubusercontent.com/38281581/80274974-ec2fbf00-8710-11ea-8a74-c47c8149a7ce.png)
> > 用Gitalk还不如直接跳转到GitHub Issues评论
> 
> emm那我该怎么办? 装回去吗(╬▔皿▔)╯

好像只能装回去了，或者通知用户手动删除缓存

PS：这条评论来自GitHub Issue https://github.com/Linhk1606/blog-source/issues/4

**Comment by MHuiG** [comment]
![image](https://user-images.githubusercontent.com/38281581/80275169-12a22a00-8712-11ea-9f1b-464ba5b37c76.png)
这个Error: Network Error就很迷。。

PS：这条评论来自GitHub Issue https://github.com/Linhk1606/blog-source/issues/4

**Comment by Linhk1606** [comment]
> ![image](https://user-images.githubusercontent.com/38281581/80275169-12a22a00-8712-11ea-9f1b-464ba5b37c76.png)
> 这个Error: Network Error就很迷。。
> 
> PS：这条评论来自GitHub Issue #4

额, 神马情况, 按Ctrl+F5强制刷新试试

**Comment by MHuiG** [comment]
> > ![image](https://user-images.githubusercontent.com/38281581/80275169-12a22a00-8712-11ea-9f1b-464ba5b37c76.png)
> > 这个Error: Network Error就很迷。。
> > PS：这条评论来自GitHub Issue #4
> 
> 额, 神马情况, 按Ctrl+F5强制刷新试试

这个是网络错误，我就是因为这个才弃用Gitalk

**Comment by Linhk1606** [comment]
> @MHuiG
> > > ![image](https://user-images.githubusercontent.com/38281581/80275169-12a22a00-8712-11ea-9f1b-464ba5b37c76.png)
> > > 这个Error: Network Error就很迷。。
> > > PS：这条评论来自GitHub Issue #4
> > 
> > 额, 神马情况, 按Ctrl+F5强制刷新试试
> 
> 这个是网络错误，我就是因为这个才弃用Gitalk

用GHelper啊

**Comment by MHuiG** [comment]
> > @MHuiG
> > > > ![image](https://user-images.githubusercontent.com/38281581/80275169-12a22a00-8712-11ea-9f1b-464ba5b37c76.png)
> > > > 这个Error: Network Error就很迷。。
> > > > PS：这条评论来自GitHub Issue #4
> > > 
> > > 
> > > 额, 神马情况, 按Ctrl+F5强制刷新试试
> > 
> > 
> > 这个是网络错误，我就是因为这个才弃用Gitalk
> 
> 用GHelper啊

其实我一直在你的源码仓库的Issue里面评论

**Comment by MHuiG** [comment]
之前看到有的主题作者直接从主题中移除了Gitalk

![image](https://user-images.githubusercontent.com/38281581/80275302-f652bd00-8712-11ea-8ba2-15c00dc1bc81.png)

然后下面再放一个Valine 哈哈

**Comment by Linhk1606** [comment]
GHelper的免费线路
![image.png](https://i.loli.net/2020/04/25/fWreVbMP2EqLdFi.png)
还有你终于不Quote Reply了哈哈, 都快成千层蛋糕了

**Comment by MHuiG** [comment]
> @Linhk1606
> GHelper的免费线路
> ![image.png](https://i.loli.net/2020/04/25/fWreVbMP2EqLdFi.png)
> 还有你终于不Quote Reply了哈哈, 都快成千层蛋糕了

已经用上啦，哈哈

**Comment by MHuiG** [comment]
Gitalk不要忘记初始化404.htm 🤣🤣🤣

**Comment by Linhk1606** [comment]
> @MHuiG
> Gitalk不要忘记初始化404.html 🤣🤣🤣
> 
> ![image](https://user-images.githubusercontent.com/38281581/80281000-a12aa180-873a-11ea-967d-c160ff12d0ad.png)
> 

OK了 :laugh:

**Comment by Linhk1606** [comment]
最终评论系统选择了Gitalk, 搜索选了Algolia~

**Comment by JalenChuh** [comment]
抛弃 valine 了？😎
我打算过几天加回去

**Comment by Linhk1606** [comment]
> @JalenChuh
> 抛弃 valine 了？😎
> 我打算过几天加回去

valine过于不安全, 而且没Gitalk好看

**Comment by JalenChuh** [comment]
> > @JalenChuh
> > 抛弃 valine 了？😎
> > 我打算过几天加回去
> 
> valine过于不安全, 而且没Gitalk好看

感觉 valine-admin 还挺好看的，安全问题嘛， admin 那开以开手动审核 😜

**Comment by inkss** [comment]
怎么突然换评论系统了

**Comment by Linhk1606** [comment]
> @inkss
> 怎么突然换评论系统了

我前几天去 @Flexiston 的站玩的时候, 亲眼看到他的Valine正在被人刷...

**Comment by Linhk1606** [comment]
Gitalk感觉更自由, Valine把Markdown直接转成HTML让人很不爽, 都不能改评论的, 而且可以匿名, 这是最烦的

**Comment by inkss** [comment]
可是这个申请的权限好大

**Comment by inkss** [comment]
我都直接在你的issue里评论的

**Comment by Flexiston** [comment]
可以用utterances

**Comment by Flexiston** [comment]
> 我都直接在你的issue里评论的

+1 😅

**Comment by Flexiston** [comment]
> > @inkss
> > 怎么突然换评论系统了
> 
> 我前几天去 @Flexiston 的站玩的时候, 亲眼看到他的Valine正在被人刷...

😅😅

**Comment by inkss** [comment]
> 😅😅

被刷是怎么回事啊

**Comment by Linhk1606** [comment]
@Flexiston

**Comment by Flexiston** [comment]
一大堆评论

**Comment by inkss** [comment]
不是有valine-admin吗

**Comment by inkss** [comment]
我是魔改了一些，

**Comment by Flexiston** [comment]
valine-admin怎么防止呀 😂

**Comment by Linhk1606** [comment]
他很有意思, 使用 一言里面的名人名言API, 昵称就是那个名人, 评论里面是他的名句🤣, 然后用的邮箱是随机的QQ邮箱, UA和时间也是乱改的

**Comment by inkss** [comment]
valine-admin，过滤内容，或者邮箱吧，我改的不多，你可以看看 MHuiG  修改后的仓库

**Comment by Flexiston** [comment]
你把box-shadow弄的这么大 🤣

**Comment by Linhk1606** [comment]
> @Flexiston
> 你把box-shadow弄的这么大 🤣

不小心搞错了, 反正准备要更新主题了, 这些东西都要调整😁

**Comment by Flexiston** [comment]
对了，我换头像了🤣🤣

**Comment by Flexiston** [comment]
@Linhk1606 你更新了

**Comment by Linhk1606** [comment]
> @Flexiston
> @Linhk1606 你更新了

更新好累啊😂

**Comment by JalenChuh** [comment]
话说 valine 用 gmail 发邮件的话，SMTP_PASS 怎么找啊，是登陆密码吗

**Comment by Linhk1606** [comment]
> @JalenChuh
> 话说 valine 用 gmail 发邮件的话，SMTP_PASS 怎么找啊，是登陆密码吗

对啊, Gooooogle账号密码

**Comment by inkss** [comment]
这个评论不能倒叙显示吗

**Comment by Linhk1606** [comment]
> @inkss
> 这个评论不能倒叙显示吗

不能吧，因为倒一次的工作量还是比较大的

**Comment by JalenChuh** [comment]
可以的

![image.png](https://p.pstatp.com/origin/137ec0000364fe4b4f577)

**Comment by Linhk1606** [comment]
这是登录以后的, 登陆前不行. 如果每次访问网页都要翻转一次的话很浪费. 翻转一次的时间复杂度大概是O(N)级的, 顶多能快到O(1/2N), 😊

**Comment by JalenChuh** [comment]
这边建议记忆化一下，有新评论的时候再 O(1/2N) 来更新正序倒序两个数组，平常查询是 O(1) 呢 😊

**Comment by JalenChuh** [comment]
> > @JalenChuh
> > 话说 valine 用 gmail 发邮件的话，SMTP_PASS 怎么找啊，是登陆密码吗
> 
> 对啊, Gooooogle账号密码

报 Connection timeout 咋办啊，不会得给他连个梯子吧

**Comment by Flexiston** [comment]
啊这
@Linhk1606 你也换头像了

**Comment by Linhk1606** [comment]
> 这边建议记忆化一下，有新评论的时候再 O(1/2N) 来更新正序倒序两个数组，平常查询是 O(1) 呢 😊

记忆化存哪? 我这是静态博客🤣

**Comment by Linhk1606** [comment]
> > > @JalenChuh
> > > 话说 valine 用 gmail 发邮件的话，SMTP_PASS 怎么找啊，是登陆密码吗
> > 
> > 
> > 对啊, Gooooogle账号密码
> 
> 报 Connection timeout 咋办啊，不会得给他连个梯子吧

你用国际版啊

**Comment by JalenChuh** [comment]
> @Linhk1606
> > > > @JalenChuh
> > > > 话说 valine 用 gmail 发邮件的话，SMTP_PASS 怎么找啊，是登陆密码吗
> > > 
> > > 
> > > 对啊, Gooooogle账号密码
> > 
> > 报 Connection timeout 咋办啊，不会得给他连个梯子吧
> 
> 你用国际版啊

数据都在国内版，数据可以备份，但是免费版不能恢复数据，烦啊

**Comment by Flexiston** [comment]
这个 Cover 有点熟悉啊😜

**Comment by Linhk1606** [comment]
> @Flexiston
> 这个 Cover 有点熟悉啊😜

哈哈，只是。。。icarus的原图是svg的，然后为啥到你那转成png啦

**Comment by Linhk1606** [comment]
> @Flexiston
> 啊这
> @Linhk1606 你也换头像了

哈，从pixiv上找的

**Comment by Flexiston** [comment]
@Linhk1606
> > @Flexiston
> > 这个 Cover 有点熟悉啊😜
> 
> 哈哈，只是。。。icarus的原图是svg的，然后为啥到你那转成png啦

手动转的
而且我是转成jpg😜

**Comment by Linhk1606** [comment]
@xaoxuu 居然改了导航栏🤣

**Comment by Linhk1606** [comment]
咕咕咕

**Comment by JalenChuh** [comment]
乒乓球 :laughing:

**Comment by Linhk1606** [comment]
> @JalenChuh
> 乒乓球 :laughing:

真的很好玩，我从小就喜欢

**Comment by Flexiston** [comment]
> > @JalenChuh
> > 乒乓球 😆
> 
> 真的很好玩，我从小就喜欢

我也喜欢 🤣

**Comment by Linhk1606** [comment]
> @Flexiston
> > > @JalenChuh
> > > 乒乓球 😆
> > 
> > 真的很好玩，我从小就喜欢
> 
> 我也喜欢 🤣

哈哈哈

**Comment by inkss** [comment]
gitalk 的正确评论姿势，跳转到相应 issue

**Comment by Linhk1606** [comment]
> @inkss
> gitalk 的正确评论姿势，跳转到相应 issue

对, 你们可以设计一个按钮, 跳转到Issue里

**Comment by Linhk1606** [comment]
> > > > blablabla
> > > blabla
> > bla
> b

**Comment by Flexiston** [comment]
> > @inkss
> > gitalk 的正确评论姿势，跳转到相应 issue
> 
> 对, 你们可以设计一个按钮, 跳转到Issue里

扒云游君的 ![emoji](https://cdn.jsdelivr.net/gh/Flexiston/cdn-emoji/valine/tieba/tieba-1.png)

**Comment by MHuiG** [comment]
直接跳转到Issue里就完事了，要什么评论系统

![](https://camo.githubusercontent.com/1f61e843cb49730c9510fb21ea549ae1d13f2bf0/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f466c65786973746f6e2f63646e2d656d6f6a692f76616c696e652f74696562612f74696562612d312e706e67)

**Comment by Linhk1606** [comment]
> @MHuiG
> 直接跳转到Issue里就完事了，要什么评论系统
> 
> ![](https://camo.githubusercontent.com/1f61e843cb49730c9510fb21ea549ae1d13f2bf0/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f466c65786973746f6e2f63646e2d656d6f6a692f76616c696e652f74696562612f74696562612d312e706e67)

不是麻烦吗, 原地评论更舒服, 而且Gitalk好看鸭

**Comment by Flexiston** [comment]
我都是issue里评论的![emoji](https://cdn.jsdelivr.net/gh/Flexiston/cdn-emoji/valine/tieba/tieba-1.png)

**Comment by Linhk1606** [comment]
> @Flexiston
> 我都是issue里评论的![emoji](https://cdn.jsdelivr.net/gh/Flexiston/cdn-emoji/valine/tieba/tieba-1.png)

Issue不能倒叙你咋不向GitHub投诉呢 ![emoji](https://cdn.jsdelivr.net/gh/Flexiston/cdn-emoji/valine/tieba/tieba-1.png)

**Comment by Linhk1606** [comment]
> 之前看到有的主题作者直接从主题中移除了Gitalk，加上Issue跳转链接
> 
> ![image](https://user-images.githubusercontent.com/38281581/80275302-f652bd00-8712-11ea-8ba2-15c00dc1bc81.png)
> 
> 然后下面再放一个Valine 哈哈

这是一条古老的评论

**Comment by MHuiG** [comment]
> > > @MHuiG
> > > > > ![image](https://user-images.githubusercontent.com/38281581/80275169-12a22a00-8712-11ea-9f1b-464ba5b37c76.png)
> > > > > 这个Error: Network Error就很迷。。
> > > > > PS：这条评论来自GitHub Issue #4
> > > > 
> > > > 
> > > > 额, 神马情况, 按Ctrl+F5强制刷新试试
> > > 
> > > 
> > > 这个是网络错误，我就是因为这个才弃用Gitalk
> > 
> > 
> > 用GHelper啊
> 
> 其实我一直在你的源码仓库的Issue里面评论

老千层饼了还是古老的千层面

**Comment by Linhk1606** [comment]
> > > > @MHuiG
> > > > > > ![image](https://user-images.githubusercontent.com/38281581/80275169-12a22a00-8712-11ea-9f1b-464ba5b37c76.png)
> > > > > > 这个Error: Network Error就很迷。。
> > > > > > PS：这条评论来自GitHub Issue #4
> > > > > 
> > > > > 
> > > > > 额, 神马情况, 按Ctrl+F5强制刷新试试
> > > > 
> > > > 
> > > > 这个是网络错误，我就是因为这个才弃用Gitalk
> > > 
> > > 
> > > 用GHelper啊
> > 
> > 
> > 其实我一直在你的源码仓库的Issue里面评论
> 
> 老千层饼了还是古老的千层面

哈哈哈哈哈哈哈哈

**Comment by Linhk1606** [comment]
https://github.com/gitalk/gitalk/issues/398 看, 这个提的多好啊😀干嘛关了

**Comment by MHuiG** [comment]
> No plan. Welcome to PR. 😉

https://github.com/gitalk/gitalk/issues/341

**Comment by xaoxuu** [comment]
> @Linhk1606
> > > > > @MHuiG
> > > > > > > ![image](https://user-images.githubusercontent.com/38281581/80275169-12a22a00-8712-11ea-9f1b-464ba5b37c76.png)
> > > > > > > 这个Error: Network Error就很迷。。
> > > > > > > PS：这条评论来自GitHub Issue #4
> > > > > > 
> > > > > > 
> > > > > > 额, 神马情况, 按Ctrl+F5强制刷新试试
> > > > > 
> > > > > 
> > > > > 这个是网络错误，我就是因为这个才弃用Gitalk
> > > > 
> > > > 
> > > > 用GHelper啊
> > > 
> > > 
> > > 其实我一直在你的源码仓库的Issue里面评论
> > 
> > 老千层饼了还是古老的千层面
> 
> 哈哈哈哈哈哈哈哈


> @Linhk1606
> > > > > @MHuiG
> > > > > > > ![image](https://user-images.githubusercontent.com/38281581/80275169-12a22a00-8712-11ea-9f1b-464ba5b37c76.png)
> > > > > > > 这个Error: Network Error就很迷。。
> > > > > > > PS：这条评论来自GitHub Issue #4
> > > > > > 
> > > > > > 
> > > > > > 额, 神马情况, 按Ctrl+F5强制刷新试试
> > > > > 
> > > > > 
> > > > > 这个是网络错误，我就是因为这个才弃用Gitalk
> > > > 
> > > > 
> > > > 用GHelper啊
> > > 
> > > 
> > > 其实我一直在你的源码仓库的Issue里面评论
> > 
> > 老千层饼了还是古老的千层面
> 
> 哈哈哈哈哈哈哈哈

怎么会这样

**Comment by inkss** [comment]
> > @Linhk1606
> > > > > > @MHuiG
> > > > > > > > ![image](https://user-images.githubusercontent.com/38281581/80275169-12a22a00-8712-11ea-9f1b-464ba5b37c76.png)
> > > > > > > > 这个Error: Network Error就很迷。。
> > > > > > > > PS：这条评论来自GitHub Issue #4
> > > > > > > 
> > > > > > > 
> > > > > > > 额, 神马情况, 按Ctrl+F5强制刷新试试
> > > > > > 
> > > > > > 
> > > > > > 这个是网络错误，我就是因为这个才弃用Gitalk
> > > > > 
> > > > > 
> > > > > 用GHelper啊
> > > > 
> > > > 
> > > > 其实我一直在你的源码仓库的Issue里面评论
> > > 
> > > 
> > > 老千层饼了还是古老的千层面
> > 
> > 
> > 哈哈哈哈哈哈哈哈
> 
> > @Linhk1606
> > > > > > @MHuiG
> > > > > > > > ![image](https://user-images.githubusercontent.com/38281581/80275169-12a22a00-8712-11ea-9f1b-464ba5b37c76.png)
> > > > > > > > 这个Error: Network Error就很迷。。
> > > > > > > > PS：这条评论来自GitHub Issue #4
> > > > > > > 
> > > > > > > 
> > > > > > > 额, 神马情况, 按Ctrl+F5强制刷新试试
> > > > > > 
> > > > > > 
> > > > > > 这个是网络错误，我就是因为这个才弃用Gitalk
> > > > > 
> > > > > 
> > > > > 用GHelper啊
> > > > 
> > > > 
> > > > 其实我一直在你的源码仓库的Issue里面评论
> > > 
> > > 
> > > 老千层饼了还是古老的千层面
> > 
> > 
> > 哈哈哈哈哈哈哈哈
> 
> 怎么会这样

套就完事儿了

**Comment by JalenChuh** [comment]
这 Mac 图标可还行

**Comment by Linhk1606** [comment]
> @JalenChuh
> 这 Mac 图标可还行

是Linux的GNOME主题包里的😄

**Comment by Linhk1606** [comment]
> @inkss
> > > @Linhk1606
> > > > > > > @MHuiG
> > > > > > > > > ![image](https://user-images.githubusercontent.com/38281581/80275169-12a22a00-8712-11ea-9f1b-464ba5b37c76.png)
> > > > > > > > > 这个Error: Network Error就很迷。。
> > > > > > > > > PS：这条评论来自GitHub Issue #4
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 额, 神马情况, 按Ctrl+F5强制刷新试试
> > > > > > > 
> > > > > > > 
> > > > > > > 这个是网络错误，我就是因为这个才弃用Gitalk
> > > > > > 
> > > > > > 
> > > > > > 用GHelper啊
> > > > > 
> > > > > 
> > > > > 其实我一直在你的源码仓库的Issue里面评论
> > > > 
> > > > 
> > > > 老千层饼了还是古老的千层面
> > > 
> > > 
> > > 哈哈哈哈哈哈哈哈
> > 
> > > @Linhk1606
> > > > > > > @MHuiG
> > > > > > > > > ![image](https://user-images.githubusercontent.com/38281581/80275169-12a22a00-8712-11ea-9f1b-464ba5b37c76.png)
> > > > > > > > > 这个Error: Network Error就很迷。。
> > > > > > > > > PS：这条评论来自GitHub Issue #4
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 额, 神马情况, 按Ctrl+F5强制刷新试试
> > > > > > > 
> > > > > > > 
> > > > > > > 这个是网络错误，我就是因为这个才弃用Gitalk
> > > > > > 
> > > > > > 
> > > > > > 用GHelper啊
> > > > > 
> > > > > 
> > > > > 其实我一直在你的源码仓库的Issue里面评论
> > > > 
> > > > 
> > > > 老千层饼了还是古老的千层面
> > > 
> > > 
> > > 哈哈哈哈哈哈哈哈
> > 
> > 怎么会这样
> 
> 套就完事儿了

就完事了

**Comment by Linhk1606** [comment]
暗黑模式其实是可以很帅的~

**Comment by jalenchuh** [comment]
画风不像博客了x [狗头]

**Comment by Linhk1606** [comment]
> @jalenchuh
> 画风不像博客了x [狗头]

那像啥?
